---
title: "Entomology Resting Household Pit Shelter Households"
output: pdf_document
header-includes:
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage[normalem]{ulem}
geometry: margin=1cm
classoption: landscape
---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = NA, 
               echo = FALSE, 
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
               cache = FALSE,
  fig.path = "figures/",
  out.width = "100%"
)
options(knitr.kable.NA = '')
```

```{r}
library(dplyr)
library(knitr)
options(digits=8)

library(kableExtra)
library(readr)
library(dplyr)
```

```{r}
# Read in the randomization results
resting_household_pit_shelter <- read_csv('../outputs/table_4_resting_household_pit_shelter.csv')
# Get the list of clusters
clusters <- sort(unique(resting_household_pit_shelter$cluster_number))

```

```{r results='asis'}  
# Print the titles/tables
for (i in 1:length(clusters)) {
  this_cluster <- clusters[i]
  this_data <- resting_household_pit_shelter %>% filter(cluster_number == this_cluster)
  this_data$`cluster_number` <- NULL
  this_data$roof_type <- gsub('_', ' ', this_data$roof_type)
  this_data$wall_type <- gsub('_', ' ', this_data$wall_type)

  names(this_data) <- gsub('_', ' ', names(this_data))
  names(this_data) <- gsub('randomization', 'random-\nization', names(this_data))

  names(this_data) <- Hmisc::capitalize(names(this_data))
  k <- kable(this_data, format = "latex",
              # longtable = TRUE,
              booktabs = TRUE,
              #align = "c", 
          row.names = FALSE) %>%
      kable_styling(latex_options = c("striped", "scale_down"), full_width = T, 
                    font_size = 7) 
  cat(paste0('# Cluster ', this_cluster, '\n\n'))
  # k <- paste0(paste0('Cluster ', this_cluster, '\\', k))
  print(k)
}
