---
title: ""
output: pdf_document
geometry: margin=1cm
classoption: landscape
---

```{r, eval = FALSE, echo = FALSE}
header-includes:
- \usepackage{booktabs}
- \usepackage{xcolor}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage[normalem]{ulem}

```


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = NA, 
               echo = FALSE, 
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
               cache = FALSE,
  fig.path = "figures/",
  out.width = "100%"
)
options(knitr.kable.NA = '')
```

\thispagestyle{empty}


```{r}
library(dplyr)
library(knitr)
options(digits=8)

library(kableExtra)
library(readr)
library(dplyr)
# Define function for adding zero
add_zero <- function (x, n) {
  x <- as.character(x)
  adders <- n - nchar(x)
  adders <- ifelse(adders < 0, 0, adders)
  for (i in 1:length(x)) {
    if (!is.na(x[i])) {
      x[i] <- paste0(paste0(rep("0", adders[i]), collapse = ""),
                     x[i], collapse = "")
    }
  }
  return(x)
}
```

```{r}
# Read in data generated by generate_metadata.R
load('health_economics_tables_followup.RData')

# Read in NTD pre-selections
ntd_efficacy_preselection <- read_csv('../../../analyses/randomization/outputs/health_economics_ntd_efficacy_preselection.csv')
ntd_safety_preselection <- read_csv('../../../analyses/randomization/outputs/health_economics_ntd_safety_preselection.csv')
```

```{r}
# Get number of ntd individuals per household
ntd_ids <- sort(unique(c(ntd_efficacy_preselection$extid, ntd_safety_preselection$extid)))
# Keep only those which are in safety
in_safety <- safety_individuals %>% filter(starting_safety_status == 'in') %>% pull(extid)
ntd_ids <- ntd_ids[ntd_ids %in% in_safety]
ndx <- v0demography_full_repeat_individual %>%
  left_join(v0demography_full %>% dplyr::select(KEY, hhid), by = c('PARENT_KEY' = 'KEY')) %>%
  mutate(in_ntd = extid %in% ntd_ids) %>%
  group_by(hhid) %>%
  summarise(n_ntd = length(which(in_ntd)))
```

```{r}
# Read in hard-coded files supplied by Paula for organizing visit control sheets:
# https://bohemiakenya.slack.com/archives/C058WT0ADBN/p1693470284107819
# cluster9 <- read_delim('health_economics_supplementary_vcs_data/HEcon VCS cluster 9.csv', delim = ';') %>%
#   mutate(VCS = ifelse(VCS == 'VCS_1', '09A', 
#                       ifelse(VCS == 'VCS_2', '09B',
#                              NA))) %>%
#   mutate(hhid = add_zero(hhid, 5))
# The below was updated by Almudena in November 2023
# https://bohemiakenya.slack.com/archives/C058WT0ADBN/p1700550483706279
cluster73 <- read_delim('health_economics_supplementary_vcs_data/HEcon VCS cluster 73.csv', delim = ';') %>%
  mutate(VCS = ifelse(VCS == 'VCS_1', '73A',
                      ifelse(VCS == 'VCS_2', '73B',
                             ifelse(VCS == 'VCS_3', '73C', NA)))) %>%
  mutate(hhid = add_zero(hhid, 5))
vcs <- read_delim('health_economics_supplementary_vcs_data/HEcon VCS per cluster.csv', delim = ';')

# The project wants some clusters to have their own visit control sheet, and others to split
# Handle this:
# exceptions <- bind_rows(cluster9, cluster73)
exceptions <- bind_rows(cluster73)
households <- left_join(households, exceptions) %>%
  mutate(VCS = ifelse(is.na(VCS), cluster, VCS))

# Narrow down to just the columns specified here: https://docs.google.com/spreadsheets/d/1Ok1JAq4RhAv0dMnVRjl38Ig-6XdEyvBJbCtMzFql9k4/edit#gid=0
subs <- v0demography_full_repeat_individual %>%
  filter(!is.na(hh_head_sub_yn)) %>%
  filter(hh_head_sub_yn == 'yes') %>%
  left_join(v0demography_full %>% dplyr::select(KEY, hhid), by = c('PARENT_KEY' = 'KEY')) %>%
  mutate(firstname = stringr::str_replace_all(firstname, "[^[:alnum:]]", "")) %>%
  mutate(lastname = stringr::str_replace_all(lastname, "[^[:alnum:]]", "")) %>%
  mutate(full_name = paste0(firstname, '  ', lastname)) %>%
  mutate(full_name = toupper(full_name)) %>%
    # mutate(full_name = gsub(r"(\\)", '', full_name)) %>%
  group_by(hhid) %>%
  summarise(hh_sub = paste0(full_name, collapse = ', '))
households_in <- healtheconbaseline %>% filter(
  hecon_household_status == 'in'
) %>% pull(hhid)

# get herd eligibility from baseline from
herd_eligibility <- 
    healtheconbaseline %>% 
  dplyr::select(hhid, herd_eligible) %>% 
  mutate(herd_enrollment = ifelse(is.na(herd_eligible), 'No', ifelse(herd_eligible == 1, 'Yes', 'No'))) %>% 
  dplyr::distinct(hhid, .keep_all = TRUE) %>%
  dplyr::select(hhid, herd_enrollment)
# get cattle ownership from both baseline OR monthly form (whichever is most recent)
cattle_ownership <- 
  bind_rows(
        healtheconbaseline %>% 
  dplyr::select(start_time, hhid, total_cattle) %>% 
  mutate(cattle_owning = ifelse(is.na(total_cattle), 'No', ifelse(total_cattle > 0, 'Yes', 'No'))) %>% 
  dplyr::select(start_time, hhid, cattle_owning),
  healtheconmonthly %>% 
  dplyr::select(start_time, hhid, total_cattle) %>% 
  mutate(cattle_owning = ifelse(is.na(total_cattle), 'No', ifelse(total_cattle > 0, 'Yes', 'No'))) %>% 
  dplyr::select(start_time, hhid, cattle_owning)
  ) %>%
  # keep only most recent observation for each household
  dplyr::arrange(desc(start_time)) %>%
  dplyr::distinct(hhid, .keep_all = TRUE) %>%
  dplyr::select(-start_time)
# Join all cattle/herd information into one object (to be joined with households data)
cattle_right <- 
  left_join(herd_eligibility, cattle_ownership)

households <- households %>%
  # keep only those "in" from health economics baseline
  filter(hhid %in% households_in) %>%
  arrange(hhid) %>%
  # get some information from v0demography
  left_join(v0demography_full %>%
              dplyr::select(hhid, village)) %>%
  # join cattle ownership and herd enrollment from baseline from
  left_join(cattle_right) %>%
  left_join(subs) %>%
  left_join(ndx) %>%
  mutate(dummy = 1) %>%
  group_by(VCS) %>%
  mutate(index = cumsum(dummy)) %>%
  ungroup %>%
  mutate(head_first_name = unlist(lapply(strsplit(household_head, ' '), function(x){x[1]}))) %>%
  mutate(head_last_name = unlist(lapply(strsplit(household_head, ' '), function(x){x[length(x)]}))) %>%
  mutate(head_first_name = stringr::str_replace_all(head_first_name, "[^[:alnum:]]", "")) %>%
  mutate(head_last_name = stringr::str_replace_all(head_last_name, "[^[:alnum:]]", "")) %>%
  mutate(household_head = paste0(head_first_name, ' ', head_last_name)) %>%
  dplyr::select(
    VCS, 
    `No.` = index,
    `Household ID` = hhid,
    Village = village,
    `Head of hh` = household_head,
    `Head of hh sub` = hh_sub,
    `Hh members` = num_members,
    `Cattle-owning` = cattle_owning,
    `NTDs participants` = n_ntd,
    `Herd enrollment` = herd_enrollment) %>%
  mutate(
    `1` = '',
      `2` = '',
    Refused = '',
    `Date hh visit` = '',
    `Herd enrolled` = '',
    Notes = ''
  ) 

# Create the individual table too
persons <- v0demography_full_repeat_individual %>%
  left_join(v0demography_full %>% dplyr::select(hhid, village, cluster, KEY), by = c('PARENT_KEY' = 'KEY')) %>%
  mutate(firstname = stringr::str_replace_all(firstname, "[^[:alnum:]]", "")) %>%
  mutate(lastname = stringr::str_replace_all(lastname, "[^[:alnum:]]", "")) %>%
  mutate(full_name = paste0(firstname, ' ', lastname)) %>%
  # mutate(full_name = stringr::str_replace_all(full_name, "[^[:alnum:]]", "")) %>%
  # mutate(full_name = gsub(r"(\\)", '', full_name)) %>%
    mutate(full_name = toupper(full_name))
# Get the new individuals from health econ new
new_persons <- starting_roster %>%
  filter(!extid %in% persons$extid) %>%
  left_join(v0demography_full %>% dplyr::select(hhid, village, cluster)) %>%
     mutate(firstname = stringr::str_replace_all(firstname, "[^[:alnum:]]", "")) %>%
  mutate(lastname = stringr::str_replace_all(lastname, "[^[:alnum:]]", "")) %>%
  mutate(full_name = paste0(firstname, ' ', lastname)) %>%
  # mutate(full_name = stringr::str_replace_all(full_name, "[^[:alnum:]]", "")) %>%
  # mutate(full_name = gsub(r"(\\)", '', full_name)) %>%
    mutate(full_name = toupper(full_name))
# Combine the new and old people
persons <- bind_rows(persons, new_persons)
  
status_is_in <-starting_roster %>% filter(starting_hecon_status == 'in')
persons <- persons %>%
  arrange(hhid, extid) %>%
  # keep only those who are "in" health economics
  filter(extid %in% status_is_in$extid) %>%
  mutate(cluster = add_zero(cluster, 2)) %>%
  arrange(hhid, extid) %>%
  filter(hhid %in% households$`Household ID`) %>%
  left_join(exceptions) %>%
  mutate(VCS = ifelse(is.na(VCS), cluster, VCS)) %>%
  mutate(dummy = 1) %>%
  group_by(VCS) %>%
  mutate(index = cumsum(dummy)) %>%
  ungroup %>%
  mutate(age = as.numeric(floor((Sys.Date() - dob) / 365.25))) %>%
  mutate(ntds_participant = ifelse(extid %in% ntd_ids & extid %in% in_safety, 'Yes', 'No')) %>%
  dplyr::select(`No.` = index,
                `Ext ID` = extid,
                Village = village,
                `Member name` = full_name,
                Age = age,
                `NTDs participant` = ntds_participant, 
                VCS) %>%
    mutate(
    `1` = '',
      `2` = '',
    Refused = '',
    `Date individual visit` = '',
    `Lost individual` = '',
    Notes = ''
  ) 

# Get new persons (from healthecon_new)

# Fake names for anonimization
if(FALSE){
  fake_names <- babynames::babynames
  fake_names <- sort(unique(fake_names$name))
  out <- c()
  for(i in 1:10000){
    out[i] <- paste0(sample(fake_names, 1), ' ', sample(fake_names, 1))
  }
  fake_names <- out
  households$`Head of hh` <- sample(fake_names, nrow(households))
  households$`Head of hh sub` <- sample(fake_names, nrow(households))
  persons$`Member name` <- sample(fake_names, nrow(persons))
}

vcs_documents <- sort(unique(households$VCS))

```


```{r results='asis', eval = TRUE}  
cat('\n\n')
# Print the titles/tables
for (i in 1:length(vcs_documents)) {
  this_cluster <- vcs_documents[i]
  this_data <- households %>% filter(VCS == this_cluster) %>%
    dplyr::select(-VCS)
  n_hh <- nrow(this_data)
  these_persons <- persons %>% filter(VCS == this_cluster) %>%
    dplyr::select(-VCS)
  # names(this_data) <- gsub('_', ' ', names(this_data))

  # Household table
  # names(this_data) <- Hmisc::capitalize(names(this_data))
  k <- kable(this_data, format = "latex",
              longtable = TRUE,
              booktabs = TRUE,
              #align = "c", 
             escape = TRUE,
          row.names = FALSE) %>%
      kable_styling(latex_options = c(#"scale_down",
                'repeat_header',

                                       "striped"
                                      ), 
                     # full_width = T,
                    font_size = 7) %>%
    add_header_above(c(" " = 9, "Absences" = 2, " " = 3)) %>%
    column_spec(1,  width = "1em")  %>%
    column_spec(2,  width = "4em")  %>%
    column_spec(3,  width = "9em")  %>%
    column_spec(4,  width = "11em")  %>%
    column_spec(5,  width = "11em")  %>%
    column_spec(6,  width = "3em")  %>%
    column_spec(7,  width = "3em")  %>%
    column_spec(8,  width = "3em")  %>%
    column_spec(9,  width = "3em")  %>%
    column_spec(10,  width = "1em")  %>%
    column_spec(11,  width = "1em")  %>%
    column_spec(12,  width = "4em")  %>%
    column_spec(13,  width = "4em")  %>%
    column_spec(14,  width = "2em")  %>%
    column_spec(15,  width = "8em")  
  
  # Individual table
    k2 <- kable(these_persons, format = "latex",
              longtable = TRUE,
              booktabs = TRUE,
              #align = "c", 
             escape = TRUE,
          row.names = FALSE) %>%
      kable_styling(latex_options = c(#"scale_down",
        'repeat_header',
                                       "striped"
                                      ), 
                     # full_width = T,
                    font_size = 7) %>%
    add_header_above(c(" " = 6, "Absences" = 2, " " = 4)) %>%
    column_spec(1,  width = "1em")  %>%
    column_spec(2,  width = "5em")  %>%
    column_spec(3,  width = "12em")  %>%
    column_spec(4,  width = "15em")  %>%
    column_spec(5,  width = "3em")  %>%
    column_spec(6,  width = "3em")  %>%
    column_spec(7,  width = "1em")  %>%
    column_spec(8,  width = "1em")  %>%
    column_spec(9,  width = "3em")  %>%
    column_spec(10,  width = "5em")  %>%
    column_spec(11,  width = "3em")  %>%
    column_spec(12,  width = "12em")  
    
  cat(paste0("\\fbox{\\parbox{5cm}{\\centering Cluster No. ", this_cluster, ' HOUSEHOLDS',  "}}\n\n"))
  cat(paste0("\\medskip\n\n"))
  cat(paste0('(Number of households: ',n_hh, ')'))
  cat(paste0("\\medskip\n\n"))
  cat(paste0('Health Economics Followup Visit Control Sheet'))
  # k <- paste0(paste0('Cluster ', this_cluster, '\\', k))
  print(k)
  cat('\\newpage')
  cat(paste0("\\fbox{\\parbox{5cm}{\\centering Cluster No. ", this_cluster, ' INDIVIDUALS',  "}}\n\n"))

  print(k2)
  # cat('\\')
    cat('\\newpage')

  #   cat(paste0("\\fbox{\\parbox{5cm}{\\centering Cluster No. ", this_cluster, ' NEW MEMBERS',  "}}\n\n"))
  # 
  # print(k3)
  # cat('\\newpage')

}
```


\end{Center}