---
title: ""
output: 
  pdf_document:
    latex_engine: xelatex
header-includes:
- \usepackage{array}
- \usepackage{booktabs}
- \usepackage{threeparttablex}
- \usepackage{pdflscape}
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \usepackage{lastpage}
- \usepackage{multirow}
- \usepackage{colortbl}
- \usepackage[labelformat = empty]{caption}
- \fancyhead[CO,CE]{PK Follow up}
- \fancyfoot[CO,CE]{This is a transitory document to assist the casual laborers with household identification.\\This document will not be retained in the study investigator site file (ISF).\\Bohemia PK Follow up Visit Control Sheets Version 1.0. Date = \today\\}
- \fancyfoot[LE,RO]{Page {\thepage} of \pageref{LastPage}}
geometry: margin=2cm
classoption: landscape
params:
  vcs: '86'
always_allow_html: true
---

\thispagestyle{fancy}

```{r, eval = FALSE, echo = FALSE}
header-includes:
- \usepackage{booktabs}
- \usepackage{xcolor}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage[normalem]{ulem}
\thispagestyle{empty}

```


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = NA, 
               echo = FALSE, 
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
               cache = FALSE,
  fig.path = "figures/",
  out.width = "100%"
)
options(knitr.kable.NA = '')
```



```{r}
library(dplyr)
library(knitr)
options(digits=8)

library(kableExtra)
library(readr)
library(dplyr)
# Define function for adding zero
add_zero <- function (x, n) {
  x <- as.character(x)
  adders <- n - nchar(x)
  adders <- ifelse(adders < 0, 0, adders)
  for (i in 1:length(x)) {
    if (!is.na(x[i])) {
      x[i] <- paste0(paste0(rep("0", adders[i]), collapse = ""),
                     x[i], collapse = "")
    }
  }
  return(x)
}
```

```{r}
# Read in data generated by generate_metadata.R
load('pk_tables.RData')


# Get some geographic information
heads <- v0demography_full_repeat_individual %>%
  filter(!is.na(hh_head_yn)) %>%
  filter(hh_head_yn == 'yes') %>%
  left_join(v0demography_full %>% dplyr::select(KEY, hhid, ward, village), by = c('PARENT_KEY' = 'KEY')) %>%
  mutate(head_name = paste0(firstname, ' ', lastname)) %>%
  dplyr::select(hhid, head_name, ward, village) %>%
  dplyr::distinct(hhid, .keep_all = TRUE)
# right <- v0demography %>% 
#   dplyr::select(hhid, ward, village)  %>%
#   dplyr::distinct(hhid, .keep_all = TRUE)
# individuals <- left_join(individuals,
#                          right) 
individuals <- individuals %>% left_join(heads)

# Add PK IDs
individuals <- 
  left_join(
    individuals,
    latest %>% dplyr::select(extid, pkid)
  )

# Create a variable to indicate which section this should be grouped in for printing
# For now, just a placeholder
individuals$VCS <- individuals$cluster

# Filter down only to those in the vcs
individuals <- individuals %>% filter(VCS == params$vcs)

vcs_documents <- sort(unique(individuals$VCS))

# Filter down only to relevant variables
# Ward	Village	HhID	Hh head name	Ext_ID	Name	DOB	Efficacy status	Absences		Notes
out <- individuals %>%
  mutate(absence1 = ' ', absence2 = ' ', notes = ' ') %>%
  # dplyr::sample_n(100) %>%
    mutate(Name = paste0(firstname, ' ', lastname)) %>%
  mutate(phone_number = ' ') %>%
  mutate(obvious_screening = 'Yes   No (specify)    ',
         safety_icf = 'Yes / No',
         pk_icf = 'Yes / No',) %>%
  dplyr::select(Group = ab,
                Cluster = cluster,
                Ward = ward, 
                Village = village,
                `HhID` = hhid,
                `Hh head name` = head_name,
                `Ext_ID` = extid,
                Name,
                # `Phone number` = phone_number,
                # DOB = dob,
                # `Efficacy status` = starting_efficacy_status,
                # `1` = absence1, 
                # `2` = absence2,
                # `Obvious screening` = obvious_screening,
                # `Safety ICF` = safety_icf,
                # `PK ICF` = pk_icf,
                `Pk ID` = pkid,
                Notes = notes,
                VCS) %>%
  arrange(VCS, HhID) %>%
  mutate(Ward = ifelse(Ward == 'RAMISI', 'RAM',
                       ifelse(Ward == 'PONGWE KIKONENI', 'PK', Ward))) %>%
  mutate(Village = toupper(Village))
use_fake_names <- FALSE
if(use_fake_names){
  fake_names <- babynames::babynames
  fake_names <- fake_names$name
  names1 <- paste0(sample(fake_names, nrow(out), replace = TRUE), ' ', sample(fake_names, nrow(out), replace = TRUE))
  names2 <- paste0(sample(fake_names, nrow(out), replace = TRUE), ' ', sample(fake_names, nrow(out), replace = TRUE))
  out$`Hh head name` <- names1
  out$Name <- names2
}
```



```{r results='asis', eval = TRUE}  
cat('\n\n')
# Print the titles/tables
for (i in 1:length(vcs_documents)) {
  this_cluster <- vcs_documents[i]
  this_data <- out %>% filter(VCS == this_cluster) %>%
    dplyr::select(-VCS, -Group)
  this_data$Cluster <- NULL
  k <- kable(this_data, format = "latex",
              longtable = TRUE,
              booktabs = TRUE,
              #align = "c", 
             # caption = paste0('FA ', params$vcs),
             escape = TRUE,
          row.names = FALSE) %>%
      kable_styling(latex_options = c(#"scale_down",
                'repeat_header',

                                       "striped"
                                      ), 
                     # full_width = T,
                    font_size = 8) %>%
    # add_header_above(c(" " = 7, "Absences" = 2, " " = 4)) %>%
    column_spec(1,  width = "2em")  %>%
    column_spec(2,  width = "8em")  %>%
    column_spec(3,  width = "4em")  %>%
    column_spec(4,  width = "15em")  %>%
    column_spec(5,  width = "5em")  %>%
    column_spec(6,  width = "15em")  %>%
    column_spec(7,  width = "4em")  %>%
    column_spec(8,  width = "14em")
  
  cat(paste0("\\fbox{\\parbox{5cm}{\\centering Cluster: ", this_cluster, "}}\n\n"))

  cat(paste0("\\medskip\n\n"))
  # cat(paste0('PFU Visit Control Sheet V2'))
  # k <- paste0(paste0('Cluster ', this_cluster, '\\', k))
  print(k)
  cat('\\newpage')

}
```

\cfoot{\thepage\ of \pageref{LastPage}}

