---
title: ""
output: 
  pdf_document:
    latex_engine: xelatex
header-includes:
- \usepackage{array}
- \usepackage{booktabs}
- \usepackage{threeparttablex}
- \usepackage{pdflscape}
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- \usepackage{lastpage}
- \usepackage{multirow}
- \usepackage{colortbl}
- \usepackage[labelformat = empty]{caption}
- \fancyhead[CO,CE]{Adverse events}
- \fancyfoot[CO,CE]{This is a transitory document to assist monitors with adverse event documentation. Date = \today\\}
- \fancyfoot[LE,RO]{Page {\thepage} of \pageref{LastPage}}
geometry: margin=2cm
classoption: landscape
params:
  vcs: 02A
always_allow_html: true
---

\thispagestyle{fancy}




```{r, eval = FALSE, echo = FALSE}
header-includes:
- \usepackage{booktabs}
- \usepackage{xcolor}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage[normalem]{ulem}
- \thispagestyle{empty}

```


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = NA, 
               echo = FALSE, 
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
               cache = FALSE,
  fig.path = "figures/",
  out.width = "100%"
)
options(knitr.kable.NA = '')
library(knitr)
library(kableExtra)
```



```{r}
library(dplyr)
library(knitr)
options(digits=8)

library(kableExtra)
library(readr)
library(dplyr)
# Define function for adding zero
add_zero <- function (x, n) {
  x <- as.character(x)
  adders <- n - nchar(x)
  adders <- ifelse(adders < 0, 0, adders)
  for (i in 1:length(x)) {
    if (!is.na(x[i])) {
      x[i] <- paste0(paste0(rep("0", adders[i]), collapse = ""),
                     x[i], collapse = "")
    }
  }
  return(x)
}
```

```{r}
# Read in data generated by generate_metadata.R
load('rmd_data.RData')
```


```{r results='asis', eval = TRUE}  
cat('\n\n')
extids <- sort(unique(ae$extid))
for(i in 1:length(extids)){
  this_extid <- extids[i]
  this_ae <- ae %>% filter(extid == this_extid)
  # AE (principle table)
  table1 <- this_ae %>%
    dplyr::select(extid, symptom = symptom_name_helper,
                  symptom_start, symptom_end,
                  symptom_still_have, 
                  symptom_seek_care, symptom_seek_care_where, seek_care_hospital_night,
                  num_nights_hospital,
                  todays_date) %>%
    dplyr::select(-extid)
  # Individual table
  table2 <- individuals %>%
    filter(extid == this_extid) %>%
    dplyr::select(-extid)
  # Visit table
  table3 <- visit_level %>%
    filter(extid == this_extid) %>%
    dplyr::select(-extid) %>%
    arrange(visit)
  table3 <- t(table3)
  
  # Make kables
    k1 <- kable(table1, format = "latex",
              longtable = TRUE,
              booktabs = TRUE,
             escape = TRUE,
          row.names = FALSE) %>%
      kable_styling(latex_options = c(#"scale_down",
                'repeat_header',

                                       "striped"
                                      ), 
                     # full_width = T,
                    font_size = 7)
      k2 <- kable(table2, format = "latex",
              longtable = TRUE,
              booktabs = TRUE,
             escape = TRUE,
          row.names = FALSE) %>%
      kable_styling(latex_options = c(#"scale_down",
                'repeat_header',

                                       "striped"
                                      ), 
                     # full_width = T,
                    font_size = 7)
  
    k3 <- kable(table3, format = "latex",
              longtable = TRUE,
              booktabs = TRUE,
             escape = TRUE,
          row.names = TRUE) %>%
      kable_styling(latex_options = c("scale_down",
                'repeat_header',

                                       "striped"
                                      ))
    
      cat(paste0("\\fbox{\\parbox{5cm}{\\centering Adverse events of ", this_extid, '',  "}}\n\n"))
  cat(paste0("\\medskip\n\n"))
  cat(paste0('Adverse events'))
  print(k1)
  cat(paste0("\\medskip\n\n"))
  cat(paste0('Participant details'))
  print(k2)
  cat(paste0("\\medskip\n\n"))
  cat(paste0('Visit details'))
  print(k3)

  cat('\\newpage')
    
}

```

\cfoot{\thepage\ of \pageref{LastPage}}

